# Generated by Django 2.1.7 on 2019-04-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_pos', models.CharField(blank=True, max_length=100)),
                ('camera_neg', models.CharField(blank=True, max_length=100)),
                ('battery_pos', models.CharField(blank=True, max_length=100)),
                ('battery_neg', models.CharField(blank=True, max_length=100)),
                ('performance_pos', models.CharField(blank=True, max_length=100)),
                ('performance_neg', models.CharField(blank=True, max_length=100)),
                ('storage_pos', models.CharField(blank=True, max_length=100)),
                ('storage_neg', models.CharField(blank=True, max_length=100)),
                ('budget_pos', models.CharField(blank=True, max_length=100)),
                ('url', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('img_url', models.CharField(blank=True, max_length=1000)),
                ('rating', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
            ],
        ),
    ]
