# Generated by Django 2.1.7 on 2019-04-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='budget_neg',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
