# Generated by Django 2.1.7 on 2019-04-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_features_budget_neg'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='negative_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='features',
            name='positive_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='features',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
