# Generated by Django 2.1.7 on 2019-04-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0003_auto_20190414_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='battery_neu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='features',
            name='budget_neu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='features',
            name='camera_neu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='features',
            name='performance_neu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='features',
            name='storage_neu',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
